### ISSUE TITLE
ConTracker inaccessible from main menu

### ISSUE THREAD

**Issue by mrlinuxfish** [raysfire/rayshud#100]
I can't seem to find a way to get the contract tracker to show up from the main menu. I'd like to do some of the contracts at some point and would like to not have to re-load the game without a hud to select a contract.

**Comment by CriticalFlaw** [comment]
The ConTracker button is the folder to the right of the rayshud title. You can also just press F2 to bring it up.

![untitled](https://user-images.githubusercontent.com/6818236/38844453-8801f5c0-41c1-11e8-8064-14ccf74215b4.png)

**Comment by mrlinuxfish** [comment]
I had tried clicking that button earlier and had nothing happen. I think TF2 was just being weird. Thanks for the help.
