### ISSUE TITLE
bug: Korean (hangul) text gets cut off

### ISSUE THREAD

**Issue by azah** [raysfire/rayshud#105]
![1](https://user-images.githubusercontent.com/9789467/40255761-4d853d36-5ab6-11e8-80ce-84b4318674c0.PNG)
![2](https://user-images.githubusercontent.com/9789467/40255762-4d96920c-5ab6-11e8-85e2-63a0f287add2.PNG)
![1](https://user-images.githubusercontent.com/9789467/40258744-937a26ee-5ac0-11e8-9e19-dad2d2f38ced.PNG)
[1, 4, and 8 are clipping at the beginning]

**Comment by azah** [comment]
This only occurs in some places, and it's only with Korean. (Tested with Japanese, Traditional Mandarin, Romanian, Ukranian, etc,- all worked fine)

**Comment by azah** [comment]
@raysfire also if I wanted to add a hangul font like `Nanum Gothic`, what would be the best way to do that?
I see some of the other fonts take unicode ranges, but Korean has several ranges [1].

[1]: https://en.wikipedia.org/wiki/Hangul

**Comment by azah** [comment]
Someone else has the opposite problem, where characters get cut off on the right:

![7c948be940d2696b4cece45692045a8e](https://user-images.githubusercontent.com/9789467/40256348-25b71c14-5ab8-11e8-9598-57e2e2a654bd.png)

**Comment by CriticalFlaw** [comment]
I'm not very good with fonts to get a proper fix out myself. If anyone else got a solution for this, please create a pull request and I'll have the code added

**Comment by azah** [comment]
@CriticalFlaw from my investigation it seems like a weird source engine bug. Nobody I spoke to had any idea about fixing it. I don't know who to talk to at this point about it :sweat_smile:

**Comment by CriticalFlaw** [comment]
If it can be replicated in the default hud, you should create a ticket here: https://github.com/ValveSoftware/Source-1-Games/issues

Otherwise, yeah there isn't much that I can do unfortunately.
