### ISSUE TITLE
Where is the Coaching button?

### ISSUE THREAD

**Issue by iRED-Me** [raysfire/rayshud#107]
I can't find where the coaching button is.

**Comment by CriticalFlaw** [comment]
There isn't one so to save space. But I could add it I suppose

**Comment by iRED-Me** [comment]
Maybe you could add it as

**Comment by CriticalFlaw** [comment]
Added in https://github.com/raysfire/rayshud/commit/29e5aed51cd50bbb04ed62ebac6f1a0538d19dff
