### ISSUE TITLE
Font Cut Off Mac

### ISSUE THREAD

**Issue by ghost** [raysfire/rayshud#11]
So whenever I play with this hud, I really love the font. But about half of the time, words are being cut a little amount of pixels either on the top or the bottom. It really annoys me, and I was wondering if there is a fix. I am on a Mac, and I did replace the font files.

**Comment by CriticalFlaw** [comment]
macos compatibility has been slightly improved in the latest version. It simply does not like Cerbetica but the way it is right now, it's playable.
