### ISSUE TITLE
Missing hp and ammo

### ISSUE THREAD

**Issue by LetSKilL** [raysfire/rayshud#111]
![image](https://user-images.githubusercontent.com/41381356/42888603-42a4e472-8ab1-11e8-85fc-0abe5611e534.png)

Help me, I want play this hud, but i cant, because i cant see hp and ammo.
How to fix this?

**Comment by CriticalFlaw** [comment]
- Does the health and ammo reappear when you input `hud_reloadscheme` into console?
- Are the health and ammo not visible the entire time you're in-game, or after some time later?
- Have you made any modifications to the hud, or is it a clean download from huds.tf or this GitHub?

**Comment by LetSKilL** [comment]
1. No
2. the entire time I in-game
3. No

**Comment by CriticalFlaw** [comment]
Can you send your zipped copy of rayshud and screenshot of your tf/custom folder. 

Disappearing elements is a recurring issue that I havent been able to replicate and therefore fix yet

**Comment by LetSKilL** [comment]
[rayshud-master.zip](https://github.com/raysfire/rayshud/files/2206522/rayshud-master.zip)
![image](https://user-images.githubusercontent.com/41381356/42894261-1214c544-8abf-11e8-975c-03b92e3dac21.png)
![image](https://user-images.githubusercontent.com/41381356/42894273-181c5952-8abf-11e8-9a96-9a5018d42381.png)
Here

**Comment by LetSKilL** [comment]
Teammates hp in spectator mode not show too

**Comment by LetSKilL** [comment]
My_custom_stuff is hitsound

**Comment by CriticalFlaw** [comment]
Thanks! The code is the same as the versions that do work and show health/ammo values. My assumption right now is that either the other stuff in custom is somehow causing issues (maybe try only having the rayshud folder in tf/custom and see if that fixes it) or the fonts used by rayshud need to be installed on your system, which wouldn't make sense because you can see other Cerbetica fonts fine

**Comment by LetSKilL** [comment]
Removing all other from custom foldier not fix this

**Comment by LetSKilL** [comment]
Yay, it works!

**Comment by LetSKilL** [comment]
Thanks!
