### ISSUE TITLE
Text in certain meters obscured

### ISSUE THREAD

**Issue by camwright** [raysfire/rayshud#113]
The text in the Mad Milk and Wrap Assassin meters for Scout is such that it can't be read when the meters are full. [Here are the meters when full](https://i.imgur.com/4GWRCuz.jpg), and [here they are empty](https://i.imgur.com/orW5fVT.jpg).

For whatever reason, this doesn't happen with certain other meters, like the Demoman's: [full](https://i.imgur.com/TCCO28D.jpg) and [empty](https://i.imgur.com/3ay9BwQ.jpg). Though I haven't tested exhaustively which meters this happens with, I have tested that it applies to Scout when either one of the Milk or Sandman are equipped, as well as both.

**Comment by CriticalFlaw** [comment]
I'm aware that this is happening. However if I remember correctly, I've tried fixing that in the past but the white bar would always go over the text, even when I've changed the zpos.

Most have the text outside of the box or no text at all but I can give it another look

**Comment by camwright** [comment]
Can you change the text color so it looks like the Demoman meter? It looks like the Demoman "Charge" text is more of a light gray.

**Comment by CriticalFlaw** [comment]
The labels used in the item effect meters for Sandman, Bonk etc. are coded differently from the Demoman's "Charge" meter - so no matter what I did, I couldn't get it to appear over the meter itself.

I did play around with having the meter labels be under the bar. What do you think?
![image](https://user-images.githubusercontent.com/6818236/43235999-cc8d5170-9050-11e8-91d8-b06f46215426.png)

**Comment by camwright** [comment]
I think that looks quite good! Is it possible to add a little more padding between the two bars? It looks a little cramped to me.

Also would you want to do the same thing with the other meters, like the Demoman "Charge" meter if technically possible, to maintain a consistent visual design?

**Comment by CriticalFlaw** [comment]
I've noticed that if there are three bars then it would take a lot of space, so I've put the labels to the side and shortened the meters a little bit. I prefer this version a lot more.

![image](https://user-images.githubusercontent.com/6818236/43236732-b52abeba-9054-11e8-8e74-9fb2a6f3e49f.png)

**Comment by camwright** [comment]
That looks awesome.

**Comment by CriticalFlaw** [comment]
Added in https://github.com/raysfire/rayshud/commit/7844231015b697b2fdb42366432c3704d916114b

You can download the latest version from GitHub to get these changes. They won't be going up on huds.tf for a little bit.

**Comment by camwright** [comment]
Great, thank you.
