### ISSUE TITLE
Thermal Thruster Meter

### ISSUE THREAD

**Issue by camwright** [raysfire/rayshud#117]
The Thermal Thruster meter seems to be using the default HUD plate, rather than a styled meter. Is it possible to style it similar to the other meters, or at least remove the BLU/RED background plate?

**Comment by CriticalFlaw** [comment]
Added in https://github.com/raysfire/rayshud/commit/4c02ccf82ac0dbbc97f64616b00c8825addc5bd5

![20180809222937_1](https://user-images.githubusercontent.com/6818236/43935834-bef4598a-9c23-11e8-85b2-7cefa759d96c.jpg)
