### ISSUE TITLE
Backpack page navigation controls (still (after 4d9d2b4)) aren't safe beyond 40 pages. 

### ISSUE THREAD

**Issue by pdatumoj** [raysfire/rayshud#121]
For backpacks in excess of 40 pages, the page navigation controls still (even after commit 4d9d2b45b32d58779daf88c6752f8795e8482b39 ) conflict with the direct access page buttons.

**Comment by CriticalFlaw** [comment]
Could you create a pull request to have your changes added to the master repo? I've taken a look at your change and it looks good.

**Comment by pdatumoj** [comment]
Not really used to github's take on git, thus some clumsiness, but request #122 is created.

**Comment by CriticalFlaw** [comment]
Thanks. Added in https://github.com/raysfire/rayshud/pull/122
