### ISSUE TITLE
Sapper Meter in Mann vs Machine

### ISSUE THREAD

**Issue by my3t** [raysfire/rayshud#124]
![image](https://user-images.githubusercontent.com/33184869/50764004-6635fd80-12ac-11e9-9a1f-53e03594fa60.png)

**Comment by CriticalFlaw** [comment]
Thanks for reporting this! It has been fixed in https://github.com/raysfire/rayshud/commit/581f8398788825c7f44825dd2c5118e3535de7c0

![20190109171847_1](https://user-images.githubusercontent.com/6818236/50932179-d1a9d780-1432-11e9-9a64-b0c2e5f6bac9.jpg)
