### ISSUE TITLE
Item colors in backpack

### ISSUE THREAD

**Issue by SpermShower1** [raysfire/rayshud#129]
Not an issue and its not really that important either but item quality colors in backpack look unpleasant. Mainly because the borders are so thin and so bright and the background is so dark that almost look like a different color. My suggestion is to make background a lighter and brighter color and either remove borders completely or make them a bit thicker and closer to background color.

**Comment by CriticalFlaw** [comment]
This sounds like it could be a good feature to add to the rayshud-installer. Could you create a ticket here please? https://github.com/CriticalFlaw/rayshud-Installer/issues/new

Thanks!

**Comment by CriticalFlaw** [comment]
Closing. Ticket moved to https://github.com/CriticalFlaw/rayshud-Installer/issues/30
