### ISSUE TITLE
How to remove this HUD?

### ISSUE THREAD

**Issue by catscarlet** [raysfire/rayshud#130]
I installed this HUD but I don't think I could get with it.
I tried to remove all the files in `steamapps/common/Team Fortress 2/tf/custom`, but I found out something didn't return to the TF2 default.
I tried to Verfied all files, even uninstalled and reinstalled, but still, a lot stuff didn't return to TF2 default.

How to remove this HUD?

**Comment by CriticalFlaw** [comment]
Can you send a screenshot of your tf/custom folder please?

**Comment by catscarlet** [comment]
Sorry I forgot to metion I'm using Linux Mint.

![Selection_006](https://user-images.githubusercontent.com/10594035/57196477-c8b7b580-6f8f-11e9-872b-d5bd78dcf9f0.png)

**Comment by CriticalFlaw** [comment]
It's possible that you had previous installed rayshud over the base TF2 files. You could try resetting all of TF2 following the instructions in the video below. Other than that I don't really have an answer for you.

https://www.youtube.com/watch?v=jT3v8XGK3gI

**Comment by catscarlet** [comment]
OK, it works.

**Comment by catscarlet** [comment]
So does that mean I can't use Steam Cloud any longer? I try to turn Steam Cloud on again and the problem comes back.

**Comment by CriticalFlaw** [comment]
No, you can turn it back on. Just make sure that when you install a custom hud, you save it in the tf/custom and never override existing TF2 files.

**Comment by catscarlet** [comment]
Sadly it doesn't.
When I turn off Steam Cloud and delete `Team Fortress 2/tf/cfg`, everything start to be normal as default.
But When I turn on Steam Cloud, the issue comes back.

**Comment by catscarlet** [comment]
The only way is to trigger Steam Cloud Sync Conflict and overwrite the Steam Cloud with new generated cfg.

**Comment by CriticalFlaw** [comment]
There should be a way to clear the Steam Cloud for the game. It's not something I'd be able to fix for you.
