### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by blank-tf** [raysfire/rayshud#131]
I'm not using transparent viewmodels. I am using custom crosshairs, though not the ones that come with the hud. ~~The crashing has always occurred when I was in-game, not on the main menu. The game doesn't immediately crash when I'm in-game. The time before it crashes seems to be variable.~~ The crash seems to happen after a round has ended and a new one starts when the announcer is counting down.

**Comment by CriticalFlaw** [comment]
Are you using the latest version downloaded from here? Do you have it extracted correctly into the tf/custom folder?

**Comment by blank-tf** [comment]
Yes, I extracted rayshud to my custom folder and the version I have is from this repo.

**Comment by blank-tf** [comment]
It also seems to occur is setup.

**Comment by gozulio** [comment]
I've also had issues crashing using rayshud. This is with the latest version of the HUD "right out of the box".
unlike blank-tf here though my crashes don't have a pattern to them. though they seem to occur most often after dying, either in the spectator camera or just after spawning.
All i know for sure is the problem goes away when i switch for a different HUD.

**Comment by CriticalFlaw** [comment]
Which operating system are you using? Also do you have either mastercomms or custom crosshairs installed separately?

**Comment by gozulio** [comment]
My current operating system is Windows 10. I do not have either of those addons installed.

**Comment by CriticalFlaw** [comment]
Does it happen most often with any particular gamemode, map or class?

**Comment by CriticalFlaw** [comment]
You could also post the log of your play session that crashed, that would help identify what caused it easier. The logs can be found in `Steam\steamapps\common\Team Fortress 2\tf\logs`

**Comment by gozulio** [comment]
It seemed to happen more often in CTF, though it was not limited to that game mode.
I do not have a logs folder in the tf directory.
When the game crashes it just crashes to desktop with no error dialogue or anything.

**Comment by CriticalFlaw** [comment]
Do you have the developer console enabled? I think enabling that will create logs

**Comment by gozulio** [comment]
I do, i've also figured out how to enable console logs, though they haven't been very helpful.
This is the log from the last crash. (happened just now, i was playing spy and strafing to avoid an engineer. The game crashed as soon as i bumped him.)

> Team Fortress
> Map: koth_viaduct
> Players: 1 / 24
> Build: 5097991
> Server Number: 1
> 
> Client reached server_spawn.
> Recognizing MM server id [A:1:4063174656:12647]
> Attemped to precache unknown particle system "blood_impact_red"!
> The server is using sv_pure 0.  (Enforcing consistency for select files only)
> Voice_Init: Using Steam voice optimal sample rate 24000
> -InV- Glitterpaws connected
> Compact freed 458752 bytes
> --- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing
> --- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing
> --- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing
> Redownloading all lightmaps
> NextBot tickrate changed from 0 (0.000ms) to 7 (0.105ms)
> No such variable "$C0_X" for material "dev/lumcompare"
> No such variable "$C0_X" for material "dev/lumcompare"
> No such variable "$C0_Z" for material "dev/lumcompare"
> No such variable "$C0_Y" for material "dev/lumcompare"
> 'spy.cfg' not present; not executing.
> No such variable "$bloomamount" for material "dev/blurfiltery_nohdr"
> No such variable "$C0_X" for material "dev/halo_add_to_screen"
> No such variable "$C0_Y" for material "dev/lumcompare"
> No such variable "$C0_X" for material "dev/lumcompare"
> No such variable "$C0_Z" for material "dev/lumcompare"
> No such variable "$C0_Z" for material "dev/lumcompare"
> No such variable "$C0_Z" for material "dev/lumcompare"
> No such variable "$bloomamount" for material "dev/blurfiltery_nohdr"
> No caption found for 'heavy.battlecry01'
> No such variable "$bloomamount" for material "dev/blurfiltery_nohdr"
> No caption found for 'medic.battlecry04'
> No caption found for 'spy.battlecry02'
> No caption found for 'engineer.battlecry06'
> No such variable "$C0_X" for material "dev/halo_add_to_screen"
> No such variable "$C0_X" for material "dev/halo_add_to_screen"
> No caption found for 'soldier.battlecry03'
> No caption found for 'pyro.battlecry02'
> No such variable "$C0_X" for material "dev/lumcompare"
> No such variable "$C0_Y" for material "dev/lumcompare"
> No caption found for 'scout.battlecry05'
> No caption found for 'demoman.battlecry06'
> No caption found for 'soldier.battlecry04'
> No caption found for 'demoman.battlecry04'
> No such variable "$bloomamount" for material "dev/blurfiltery_nohdr"
> No such variable "$C0_X" for material "dev/lumcompare"
> No such variable "$C0_X" for material "dev/halo_add_to_screen"
> No such variable "$C0_Z" for material "dev/lumcompare"
> No such variable "$bloomamount" for material "dev/blurfiltery_nohdr"
> No such variable "$bloomamount" for material "dev/blurfiltery_nohdr"

None of these logs where in the log from the crash before though, The rest of the log is here.
[console.log](https://github.com/raysfire/rayshud/files/3245208/console.log)

**Comment by CriticalFlaw** [comment]
Could you repost the link to the complete log please? The current link isn't working for me

**Comment by CriticalFlaw** [comment]
I've played with the latest rayshud for about two hours and haven't yet been able to reproduce the crash. It's possible that there might be something in the base TF2 files that's causing the issue. You could try resetting all of TF2 following the instructions in the video below. If you'll choose to do so, remember to backup all of your configs. I'm sorry I wasn't able to fix the problem for you otherwise.

https://www.youtube.com/watch?v=jT3v8XGK3gI

**Comment by blank-tf** [comment]
So I deleted all of my configs in tf/cfg and now the issue is not happening anymore. Thank you for all the help
