### ISSUE TITLE
Improper Killstreak position

### ISSUE THREAD

**Issue by Detenog** [raysfire/rayshud#133]
I'll suppose this only happens to me, but when I play with any Killstreak weapon I notice that The counter is way down than usual. (I'm not sure if this is a problem or a feature)

Screenshot:
https://steamcommunity.com/sharedfiles/filedetails/?id=1821113671

**Comment by CriticalFlaw** [comment]
That is the intended position of the killstreak counter afaik

Does it change position in different resolutions?

**Comment by Detenog** [comment]
I use 1920x1080. If it is intended like that. I would not argue anymore.

**Comment by CriticalFlaw** [comment]
That's the intended position. I'm on 1920x1080 as well.

![20190804095107_1](https://user-images.githubusercontent.com/6818236/62424514-7aed3f00-b69d-11e9-876c-b8a951187495.jpg)
