### ISSUE TITLE
Main menu broken

### ISSUE THREAD

**Issue by waylon531** [raysfire/rayshud#135]
The main menu is completely broken as of commit https://github.com/raysfire/rayshud/commit/abd9296fc5d1b097b95a8b362b47057265d5ad42

Before that commit everything looks normal, but as soon as I'm on that commit the main menu looks like this:
![rayshud](https://user-images.githubusercontent.com/1129192/62407319-234eb680-b56b-11e9-9ae5-33dcfa648ed8.png)

**Comment by CriticalFlaw** [comment]
Hey there. How did you install the latest version? Did you overwrite the existing one with the latest or do a clean install?

Also did you do it manually or use the installer?

**Comment by waylon531** [comment]
I installed using `git clone`, and to update to the latest version I just did a `git pull`. The main menu was broken as soon as I updated to the latest commit so I went back through previous commits with `git revert` until I found the one that broke the menu. My clone of the repository is clean, no extra files have been modified, so it should be pretty much the same as a clean install.

**Comment by CriticalFlaw** [comment]
That's odd. Can you try removing that install of rayshud and installing it fresh again either through `clone` or `Download ZIP` - I'm not seeing this issue on my side, so I can only assume that there is some file conflict because a lot has been changed in the back.

**Comment by waylon531** [comment]
I just did a clean install via `git clone`, I'm getting the same issue.

**Comment by CriticalFlaw** [comment]
May I see a screenshot of your tf/custom and tf/custom/rayshud directories please?

**Comment by waylon531** [comment]
Here's their contents:
```
 $ ls custom/
rayshud  readme.txt  workshop
 $ ls custom/rayshud 
customizations  info.vdf  materials  README.md  resource  scripts  sound
```

and here's the `git status`, the only thing that's been changed is the sound.cache
```
 $ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	sound/sound.cache

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by CriticalFlaw** [comment]
Is this on Linux?

**Comment by waylon531** [comment]
Yep! Here's my full system information as reported by Steam: https://pastebin.com/UYBN1XpP

**Comment by CriticalFlaw** [comment]
I believe the issue might then be with the way Linux reads file systems. https://github.com/raysfire/rayshud/commit/abd9296fc5d1b097b95a8b362b47057265d5ad42 changes the way customizations are loaded, namely using #base to read actual file contents from the file path specified. 

In case of **rayshud/resource/ui/mainmenuoverride.res** the filepath for the contents is: `#base "../../customizations/Main Menu/mainmenuoverride.res"`

I think because the **Main Menu** folder either has upper case letters or a space, Linux has trouble finding the path and so the main menu doesn't get loaded properly. Changing either one of those should fix the problem but it'd need to be verified first.

**Comment by waylon531** [comment]
Looks like you were right! I renamed the Main Menu folder to main_menu, changed both of the lines in the override file, and the main menu is working again. I just made a pull request as well.

**Comment by CriticalFlaw** [comment]
Awesome, thanks! I'll merge the pull request, then rename the remaining customization directories. Closing.
