### ISSUE TITLE
Hud locks after opening the "new item acquired!" screen

### ISSUE THREAD

**Issue by omperus** [raysfire/rayshud#137]
![image](https://user-images.githubusercontent.com/4312673/63218085-06001780-c129-11e9-87cc-b97e69cda044.png)

If you open the "new item acquired!" ⚠ screen before looking for a match, it works as intended.
But if you open it after exiting a match, or while in one, the screen locks and all buttons stop responding (only exiting the game works), hud_reloadscheme doesn't fix it either.

The only solution is to restart the game.

This problem only started in the latest version that i applied from the updated installer, previous versions didn't have this issue.

**Comment by CriticalFlaw** [comment]
It's a common bug, found in various other custom huds. The workaround is usually to just press the `Enter` key, I don't think it can be fixed at this time.

**Comment by CriticalFlaw** [comment]
Closing. This is an engine bug with a workaround (pressing the `Enter` key bypasses the screen).
