### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by Axxbiotic** [raysfire/rayshud#140]
Whenever I try to use the current version of rayshud, my game will crash with no prior warning.
I tried reinstalling, removing all my custom files and what else, yet it still crashes.

OS is Win10; I'm using mastercom low (current version).
The old version of rayshud I'm currently using is still working without crashing my game

**Comment by Axxbiotic** [comment]
Console logs. Game crashed after I pressed the "disconnect" button.
This was an unusualy long session with no crashes, until I disconnected from that server
https://pastebin.com/TGebkE70

**Comment by CriticalFlaw** [comment]
The logs don't indicate an issue with the hud. If you can send me the working version you have on hand, I'll see if there is a potential cause for the issue. Otherwise it might be a game files/config issue.

**Comment by Axxbiotic** [comment]
As stated before, I tried out the HUd is a completly unmodified game, yet is still caused iddues
I'll try to get you better log files

**Comment by Axxbiotic** [comment]
Here is the hud version I'm currently using.


[rayshud-master.zip](https://github.com/raysfire/rayshud/files/3790715/rayshud-master.zip)

**Comment by Axxbiotic** [comment]
more logs, had leave out things at the beginning, but only the end should matter

https://pastebin.com/1gayZpL8

**Comment by Axxbiotic** [comment]
doesnt seem like the console logs have any relevant info

**Comment by electricman226** [comment]
The console in Source Engine will often not have any crash info because it's not meant for that; crash dumps are.

You could attach the crash dump, but that's quite extreme and the problem probably isn't that deep. When exactly does the crash occur, and is it consistent?

**Comment by CriticalFlaw** [comment]
A crash dump could be useful. Because when comparing hud files, I haven't found anything other than I've noticed you've added a ScopeRemoval animation and some txt files - I don't expect those to be the cause of a crash, but I must ask - did you make the same modifications to the latest version as well?

**Comment by Axxbiotic** [comment]
yes I did and I tried it with and without the scope removal thing

**Comment by Axxbiotic** [comment]
These are the most recent tf2 related crashes i found in steam\dumps


[dumps.zip](https://github.com/raysfire/rayshud/files/3796001/dumps.zip)

**Comment by Axxbiotic** [comment]
Anyone?

**Comment by CriticalFlaw** [comment]
Doesn't seem like the crashes are being caused by the HUD. The error on the crash log is generic, usually fixed by doing a clean OS reboot, verifying game files, updating graphics drivers. If this was a HUD related crash, it'd be noted in the logs or reported more widely.

**Comment by electricman226** [comment]
I did open the crash dumps a little while ago, and like I said, they gave us very little info as to why.

What I can tell you is that the crash is always at the same address, meaning whatever is causing it is consistent.

**Comment by Axxbiotic** [comment]
It only happens with the current version of the HUD, I clean installed windows and did all the other steps, still same issue

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of your Rd/custom folder?

**Comment by CriticalFlaw** [comment]
Closing because this issue cannot be reproduced and hasn't been reported elsewhere.
