### ISSUE TITLE
Matchmaking menu doesn't stretch down whole screen

### ISSUE THREAD

**Issue by dankdonk** [raysfire/rayshud#141]
![image](https://user-images.githubusercontent.com/50967822/71550309-e27c9180-2992-11ea-8fda-55b2bafd49aa.png)

**Comment by CriticalFlaw** [comment]
Removed the dashboard dimmer from the main menu (both classic and default versions).

Thank you for reporting it.

**Comment by CriticalFlaw** [comment]
This change will be reverted in the next update because removing the dimmer disables the ability to close the matchmaking panel by clicking anywhere on the screen. A number of users have reported that as an issue
