### ISSUE TITLE
Ammo clipping

### ISSUE THREAD

**Issue by WoniMK7** [raysfire/rayshud#144]
The ammo number is clipping with the icon on the medic's target ID. This seems to only happen on single digits. 
![20200414212129_1](https://user-images.githubusercontent.com/15377600/79265304-2ccc4480-7e96-11ea-85bb-6eb68e505bc6.jpg)

Other issue: I selected "damage above health in installer (4.0) but it only works in "minmode". Else it shows over ammo.

**Comment by CriticalFlaw** [comment]
I've pushed the changes to [move the ammo icon](73ddc8ab54c149224c96a42fe5542c687066e322) and set the [correct position for the damage value](3910db093a29c04e27d205a5e0be44b32c24c2d0).

The installer has also been updated to correct the issue, version release 4.0.1.

https://github.com/CriticalFlaw/rayshud-Installer/commit/cd6c49398b0a1ec81c213e5746f9340ad5ed8af1

Thank you for reporting these issues.
