### ISSUE TITLE
Rayshud causing missing water textures.

### ISSUE THREAD

**Issue by theawesomecrispy** [raysfire/rayshud#148]
When I join any map with water, the water becomes purple and it makes it purple because of the missing texture. The water textures only show up as missing when I'm not in the menu as shown in the screenshots. https://prnt.sc/tdq0io https://prnt.sc/tdq0bi

**Comment by dankdonk** [comment]
This isn't caused by missing textures. That's not how Source works. If the texture was missing, it would be a flat, magenta and black checkered plane without any rippling. 
Have you tried seeing what happens when you remove rayshud from your tf/custom folder?

**Comment by theawesomecrispy** [comment]
When I remove rayshud it's completely normal with the correct water textures, when i put rayshud back in it does this to me. Doesn't happen with flawhud but I like the look of rayshud more and wish to use it.

**Comment by CriticalFlaw** [comment]
Are you using the latest version of rayshud, without any modifications like transparent viewmodels or crosshairs?

**Comment by theawesomecrispy** [comment]
I have no crosshairs from the hud, no transparent viewmodels, and I'm using the latest release from 29 days ago. The only modifications I've made with the hud are the colors. https://prnt.sc/tdqrxy

**Comment by CriticalFlaw** [comment]
Does this happen if you download and install a copy of rayshud directly from GitHub instead of through the installer?

**Comment by theawesomecrispy** [comment]
Seems to only be a problem when I use the version downloaded through the installer. When I got a fresh install of the rayshud-master the problem goes away. Sucks that I will lose some of my customizations, but the hud is so good that I'll use it anyways. :)

**Comment by theawesomecrispy** [comment]
Edit: Changes nothing after further testing, will be switching back to flawHUD.
