### ISSUE TITLE
Per-Player Tournament Ready System

### ISSUE THREAD

**Issue by jpenton** [raysfire/rayshud#15]
![](http://puu.sh/iMfH7/20240bee22.jpg)

As the title says, tf2 now has a per-player tournament ready system. To enable it, you can do "mp_tournament_readymode 1; mp_tournament_readymode_min 0" and make sure that SOAP DM is unloaded. If it's loaded, then you can't walk in game (although you can shoot).

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/raysfire/rayshud/commit/35db3dc6120b5275c57404d2843dac79b6554923
