### ISSUE TITLE
No sapper indicator

### ISSUE THREAD

**Issue by realSaddy** [raysfire/rayshud#151]
G'day, 

I'm a long time user of this hud though it has always been missing an essential feature for the spy. The default hud displays information on the current sapped buildings (see [this demonstration video](https://www.youtube.com/watch?v=csb-3NPXK9g)), but rayshud does not show any indicator. I'm unsure if there is a particular setting I need to turn on, or if this is simply not added yet.

I appreciate your continued support of this hud,
Saddy

**Comment by CriticalFlaw** [comment]
Hello. Does it still not show as of the recent version (v2020.0808)? Try to reload the HUD while in-game (hud_reloadscheme in console) and try sapping again, see if that fixes the issue

**Comment by realSaddy** [comment]
I am on the newest version (v2020.0808). Reloading the scheme in-game did seem to fix the issue though! Not sure why it requires a reload to begin with, but I'll create a keybind for now.

Thanks!

**Comment by CriticalFlaw** [comment]
It's an odd game bug where it changes the sapper and Engineer's building panels' vertical position. It's then restored with reloading the HUD. You can also use the reload HUD button on the right hand side of the main menu. Sorry for the inconvenience
