### ISSUE TITLE
Engineer's PDA information is underneath chat output

### ISSUE THREAD

**Issue by gunr2171** [raysfire/rayshud#153]
Using v2020.08.08 - 43aae9b98b5602fafaee06f1380d9798986558b9. 1080p monitor.

![image](https://user-images.githubusercontent.com/8290105/91648095-5cd54800-ea31-11ea-86ef-56915dbdd629.png)

This happens at the start of every server, and _sometimes_ when respawning. I can fix it temporarily by clicking "Minmode tottle" twice.

This can also be seen while waiting to respawn, though if I did my temp fix it will only be in that state until I respawn, it's fine once I'm playing.

![image](https://user-images.githubusercontent.com/8290105/91648187-74f99700-ea32-11ea-95ee-c50138a055a5.png)

For reference, this is what it looks like when I fix it - the panel is on the middle of the left edge.
![image](https://user-images.githubusercontent.com/8290105/91648273-65c71900-ea33-11ea-87f8-ec2744de3de0.png)

**Comment by CriticalFlaw** [comment]
It gets slammed up there by the game. Use the Reload HUD button on the right hand side of the main menu to correct it. Alternatively enter `hud_reloadscheme` into console

**Comment by gunr2171** [comment]
Oh, THAT'S what that button does! I was so confused at what it did.

Ok, thanks for the advice. TF2 is old, I guess that's all we can do about it : (
