### ISSUE TITLE
Black background on vaccinator uber meter

### ISSUE THREAD

**Issue by Shtuffs** [raysfire/rayshud#154]

**Comment by CriticalFlaw** [comment]
Can you post a screenshot, please?

**Comment by Shtuffs** [comment]
![image](https://user-images.githubusercontent.com/46979803/93721761-1b334b00-fb60-11ea-95b5-40a177659372.png)

**Comment by CriticalFlaw** [comment]
Thanks. That was added on purpose so that the the Ubercharge percentage on its own can still display the shadow. 

Otherwise you'd see the shadow of the percentage while equipping the vaccinator

**Comment by Shtuffs** [comment]
wdym?

**Comment by CriticalFlaw** [comment]
You know how the Ubercharge percentage has a drop Shadow? When you equip the Vaccinator it's still being shown. 

The black background you're seeing is covering up that drop Shadow, so it doesn't look too odd.

**Comment by Shtuffs** [comment]
ah
