### ISSUE TITLE
Sentry health is still smaller than it should be even after the patch

### ISSUE THREAD

**Issue by Shtuffs** [raysfire/rayshud#158]
I know that there was a fix applied to help fix the sentry health, but it's still too small. In case you need to see it again:

![image](https://user-images.githubusercontent.com/46979803/100139376-623e0500-2e5d-11eb-98a2-87495e8e16b7.png)

**Comment by CriticalFlaw** [comment]
Closing. Sentry health size has been increased in the latest version.
