### ISSUE TITLE
Downloaded file is being opened in VLC

### ISSUE THREAD

**Issue by QRANDXM** [raysfire/rayshud#159]

**Comment by QRANDXM** [comment]
.

**Comment by CriticalFlaw** [comment]
Can you please post a screenshot of the file when you downloaded it.

**Comment by QRANDXM** [comment]
[image: rAyShUd..PNG]

**Comment by CriticalFlaw** [comment]
The screenshot isn't posting. What I think is happening is that you're associating VLC with zipped folders, which is incorrect. You'll need to download 7zip or WinRAR and use that to open the downloaded file.
