### ISSUE TITLE
Quality Color Borders only display on hover

### ISSUE THREAD

**Issue by MasterEric** [raysfire/rayshud#16]
The issue can be seen here: http://imgur.com/a/lft2b

The quality color borders that normally show when "Show Quality Color Borders" is enabled only show on hover with the newest update. When not hovering, they are a darker gray than normal.

The borders display correctly when the mouse is over the item, but are the default gray when the mouse is away from the item.

EDIT: If you select "No Item Borders", all items are a lighter shade of gray, and if you select "Show Marketable Borders Only", items with special qualities turn dark gray while the items without special qualities stay the same color.

**Comment by Yttrium-tYcLief** [comment]
Seeing this in just about every custom HUD right now. Gun Mettle broke it but I'm not really sure how.
