### ISSUE TITLE
Alternate Mode Selection Panel

### ISSUE THREAD

**Issue by GGamer2042** [raysfire/rayshud#162]
so everything is supposed to darken except the gamemode list when pressing that right? but it doesnt, IT JUST DOES'NT and its infuriating as fuck so please fix this
![image](https://user-images.githubusercontent.com/79525322/108859042-41c14a80-7606-11eb-9916-33c0c046e756.png)

**Comment by GGamer2042** [comment]
see? everything below the list is still lit as fuck

**Comment by CriticalFlaw** [comment]
That cannot be fixed because Valve hard-coded the dimmer to not cover the full screen. There are two possible solutions and neither one is perfect;

1. Remove the dimmer entirely by hackish means, but that will disable the ability to close the menu by clicking anywhere on the screen which a lot of users do, so that's not a good solution.
2. Redesign the menu to be on the bottom to cover the lit area. It's a better solution but as I've seen in flawhud, a number of users did not like it and were asking how to revert it soo that I guess is not an ideal solution either. But I will consider it

**Comment by GGamer2042** [comment]
@CriticalFlaw can you keep the normal version and also have the no2 solution'd seperately (it is not necessary to constantly update the solution'd version, volvo doenst give major updates anyways) (couldnt think of any other word other than solution'd lulz)

**Comment by GGamer2042** [comment]
wait lemme try flawhud to see what exactly u mean

**Comment by GGamer2042** [comment]
by the way, are you rays? also why is there 2 versions of rayshud on huds.tf
one is uploaded by "rays :3" and other is uploaded by you, is the rays uploaded version fake?

**Comment by GGamer2042** [comment]
oh, I dont have a big problem with that. gonna take some getting used to but its alright

**Comment by GGamer2042** [comment]
wait a second, how are u even supposed to close the menu without the dimmer lmao
im talking about the first solution, anyways second solution is better

**Comment by CriticalFlaw** [comment]
- You'd have to click on the arrows on the menu in order to close it if there's no dimmer.
- No, I took over support for rayhud from raysfire after he left TF2
- Adding the alternate menu as a customization option is doable, but it would take time and I'm busy with other projects right now.

**Comment by GGamer2042** [comment]
1. hmm i dont see any arrows, probs coz of toonhud
2. oh
3. take your time, also wouldnt it be easier to make it a seperate DOWNLOAD instead of including it in the hud as a setting?
> * You'd have to click on the arrows on the menu in order to close it if there's no dimmer.
> * No, I took over support for rayhud from raysfire after he left TF2
> * Adding the alternate menu as a customization option is doable, but it would take time and I'm busy with other projects right now.

**Comment by CriticalFlaw** [comment]
Added in 37603a8118b9793c9c545e01479992d1b09d2afc. This will be released in the next version. Thank you.

![20210702211556_1](https://user-images.githubusercontent.com/6818236/124339197-b9861f80-db7a-11eb-8373-8a363c1a2153.jpg)
