### ISSUE TITLE
Strange Black Bar in Warming Up

### ISSUE THREAD

**Issue by thejaviertc** [raysfire/rayshud#163]
When you are in Warming Up, a strange black bar appear below the current players.

It's normal?
![image](https://user-images.githubusercontent.com/45662206/109231225-71b74c00-77c6-11eb-9c98-04828f8fb5cf.png)

**Comment by CriticalFlaw** [comment]
That looks like a leftover from the match HUD. Will need to remove.

**Comment by CriticalFlaw** [comment]
Fixed in 3d9d0684b148d5b834aacd90482a504fd64f27a6. Thank you for reporting it.
