### ISSUE TITLE
Can you change the background image for the main menu?

### ISSUE THREAD

**Issue by Pixelody-Chiptune** [raysfire/rayshud#165]
Just think it looks kinda out of place.
Looks weird next to TF2 Cartoony artstyle.

**Comment by CriticalFlaw** [comment]
There's a Steam Community guide on how to change backgrounds: https://steamcommunity.com/sharedfiles/filedetails/?id=1514650207

The only difference that's applicable to rayshud is that the backgrounds are in `rayshud\materials\console\backgrounds` and assuming you're using the default main menu, you'll only want to replace `background_modern.vtf` and `background_modern_widescreen.vtf`
