### ISSUE TITLE
Misaligned item inspect panel

### ISSUE THREAD

**Issue by Silexos** [raysfire/rayshud#168]
Noticed the item inspect panel is misaligned while using it in the middle of a game. It's in the proper corner position while spectating however.

![corner_inspect_panel](https://user-images.githubusercontent.com/85089160/123551306-0fe00200-d726-11eb-9509-845504b7cdf0.jpg)
![misalligned_inspect_panel](https://user-images.githubusercontent.com/85089160/123551307-10789880-d726-11eb-8f98-98945cd098a6.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 8c07156e860e07404a92a274f4a1f5a8874007ab. Will be released in next update. Thanks!
