### ISSUE TITLE
Misaligned building damage/sapper icons

### ISSUE THREAD

**Issue by Silexos** [raysfire/rayshud#169]
When playing I noticed that the building damage/sapper indicators are misaligned for any building that is not a sentry.

![misalliged_pda_repair](https://user-images.githubusercontent.com/85089160/123551380-52094380-d726-11eb-924a-f59230483ea9.jpg)
![misalligned_pda_sapper](https://user-images.githubusercontent.com/85089160/123551381-52a1da00-d726-11eb-9943-7a95f5a215f7.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in c3ac2a1bbb189b4800fc7631f0dc51b3c3de9343. Will be released in next update. Thanks!
