### ISSUE TITLE
Weapon Collection name highlight not positioned correctly

### ISSUE THREAD

**Issue by SnubbleJr** [raysfire/rayshud#17]
Just a little thing, thought you'd like to know

![image](https://cloud.githubusercontent.com/assets/2880214/8785675/5b95bb12-2f21-11e5-84f0-2c36ccb9fdf7.png)
![image](https://cloud.githubusercontent.com/assets/2880214/8785688/6d8e149a-2f21-11e5-905a-dc8e53cfc37e.png)
![image](https://cloud.githubusercontent.com/assets/2880214/8785734/ae029938-2f21-11e5-80ce-be8b00c26357.png)

**Comment by raysfire** [comment]
I believe this is due to the font I'm using, but I'll look into this further.
