### ISSUE TITLE
Long Medigun names clip with the killstreak counter

### ISSUE THREAD

**Issue by Silexos** [raysfire/rayshud#170]
While playing I found that Medic's with long custom names on their Medigun will clip with the hud's killstreak counter. This is also the case when healing other Medics if they happen to have a long name. This issue doesn't happen while in minmode since the placement of the hud elements shifts upwards away from the heal target/Medic's name.

![long_names_medic](https://user-images.githubusercontent.com/85089160/123551478-c93ed780-d726-11eb-962d-d75a07d06d29.jpg)
![long_names_while_healing](https://user-images.githubusercontent.com/85089160/123551480-ca700480-d726-11eb-9c2b-d0d94db33067.jpg)
![medigun_min_mode](https://user-images.githubusercontent.com/85089160/123551482-cba13180-d726-11eb-813e-fc1db188efd4.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 7211d8916df735840e5b04d5164799493792a10e. Will be released in the next update. Thank you.
