### ISSUE TITLE
Old charge meter

### ISSUE THREAD

**Issue by Scoutman01** [raysfire/rayshud#174]
You should revert back the charge meter to the old one made by rays, i think they look way better and you can change the charge meter label color to what it used to be
![6fXYbi9](https://user-images.githubusercontent.com/50184129/126763536-29b46142-200b-4e04-81ff-4d0b511d1279.png)

**Comment by CriticalFlaw** [comment]
This was back when you could change the label color. Now your only options are black and white. With the former it will look like the meters in flawhud.

Will give it a try when I have some free time and we'll see if it will be worth adding in as an alternate option.

**Comment by Scoutman01** [comment]
Here what's it look like with the current rayshud version:
![20210724180039_1](https://user-images.githubusercontent.com/50184129/126874233-6a7b20a1-0068-4867-8bab-99458dfeca76.jpg)

I just took the files from this version : https://huds.tf/site/s-rayshud

**Comment by CriticalFlaw** [comment]
I've tried it out as well, and I think the black doesn't look as good on those bars at the grey did in the old rayshud. Also the white labels on the side of the meter, visually is similar to the counters like demoman heads, engineer revenge etc. So I think it'd be best to keep the item meters as the are for now.

**Comment by Scoutman01** [comment]
Hey i managed to change to meter label color thanks to Healing Sentry

take the item meter file and the entry in hudlayout (demopipes,democharges,itemeffectmeter) from the last version of rayshud made by raysfire  :https://huds.tf/site/s-rayshud

In clientscheme_colors add the following lines : 
```
Label.DisabledFgColor1		"150 150 150 0"		// Control visible 1 enabled 0 color. This controls text shadow
Label.DisabledFgColor2		"150 150 150 255"		// Control visible 1 enabled 0 color. This controls main text

```

and for each meter label change enabled to 0

here's the result : 
![20211002133948_1](https://user-images.githubusercontent.com/50184129/135714745-dc2d415a-4424-4a16-85ec-bd7d07c3666b.jpg)
![20211002134053_1](https://user-images.githubusercontent.com/50184129/135714746-8f8d4267-f7ff-4eeb-ba56-869398171c65.jpg)

some elements might overlaps with the charge meter like the target id

**Comment by CriticalFlaw** [comment]
Can you create a PR for this please? If the overlaps can be fixed then this can be added in. Thanks!

**Comment by CriticalFlaw** [comment]
Implemented in https://github.com/raysfire/rayshud/commit/58ac450cef805511c25d1d16d18994d6d393f893
