### ISSUE TITLE
Misaligned inspect panel both in killcam and friendly inspect

### ISSUE THREAD

**Issue by Silexos** [raysfire/rayshud#175]
After playing for a bit I noticed that the inspect panel in killcams frequently covers up the enemy player's name. After about three games, I noticed it would be misaligned for every killcam. Additionally I checked other instances of the item panel and noticed it is out of position when inspecting a friendly player. It should be noted that the inspect panel is correctly positioned when spectating. 

![20210724022516_1](https://user-images.githubusercontent.com/85089160/126865177-63e14140-8d05-4a9c-b801-f0a047509091.jpg)
![20210724022543_1](https://user-images.githubusercontent.com/85089160/126865178-645ee27f-9e9b-4b9d-8cf4-81cc17098dc6.jpg)
![20210724022924_1](https://user-images.githubusercontent.com/85089160/126865183-57a19cde-eebc-416a-af9c-a1f74b57c1c4.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 911fdbefda533ad312e212c8e0c12b6348add6f9. Please download the latest GitHub version, thanks.
