### ISSUE TITLE
Notifications Icon Absent

### ISSUE THREAD

**Issue by jumper-cable-morty** [raysfire/rayshud#176]
Updated to the latest commit and the notifications icon is gone from both the default menu and the classic. I know it's missing rather than just having no notifications because I can hear the sound for it that usually plays whenever I launch, and when going into the items menu it says there are pending alerts.

**Comment by Xeromere** [comment]
Can confirm I have this issue as well. Installed through tf2hudeditor, but i'm unsure if this is happening to manual installs as well. Weeks ago the same issue was happening but I could still click and open notifications, but now the area to click has outright disappeared as well.

**Comment by CriticalFlaw** [comment]
Fixed in 10b43f5aee50c9f3916945835714a05cb89fcc23. Please download the latest GitHub version, thanks.
