### ISSUE TITLE
Spy disguise panel is cutoff

### ISSUE THREAD

**Issue by barbiehunter** [raysfire/rayshud#177]
The text of the Disguise does not match the name & weapon.

![image](https://user-images.githubusercontent.com/38357837/130324560-aee1e640-c414-4fbd-abdf-f5d39a2d33c3.png)
![image](https://user-images.githubusercontent.com/38357837/130324672-a82ac6ef-cd3d-4cf8-93d7-37e3129ad8e6.png)

**Comment by CriticalFlaw** [comment]
Fixed in 7eafccb54014c16a424912485f724c4a168ba659
