### ISSUE TITLE
Start search button on main screen

### ISSUE THREAD

**Issue by Acmpo6ou** [raysfire/rayshud#178]
Hi and thanks for your HUD!

I just wanted to ask, maybe you know how to add the "start search" button to main screen, somewhere at the top near the "quit" and "find game" buttons. It's just whenever I want to queue for casual I have to go to "find game" -> "casual" -> "start search" and that's a lot of clicks. Maybe you know how to help me. That'll be cool!

**Comment by CriticalFlaw** [comment]
User probably figured that this function is not possible because the user needs to select their maps before queuing

**Comment by Acmpo6ou** [comment]
> User probably figured that this function is not possible because the user needs to select their maps before queuing 

Not at all, you don't need to select the maps they are already selected. I've closed the issue because I'm not playing **Casual** anymore, only community servers. So there is no need in this button anymore.
