### ISSUE TITLE
Text on the scoreboard is in the wrong places

### ISSUE THREAD

**Issue by Dilski** [raysfire/rayshud#18]
http://i.imgur.com/Tsf0PCy.jpg

**Comment by obla** [comment]
What version of the hud are you using? Try updating your HUD

**Comment by Dilski** [comment]
Downloaded from the gitub repo this morning.(v3.98)

**Comment by chauffer** [comment]
3.98 is clearly *not* the latest version. 08980faff4a4833d0b9a46c1e77afaada781f3f1

https://github.com/raysfire/rayshud/archive/master.zip will always download the latest version.

**Comment by raysfire** [comment]
Issue closed; needed to update to newest version
