### ISSUE TITLE
Payload Race objective is cutoff

### ISSUE THREAD

**Issue by Epicbigfoot** [raysfire/rayshud#180]
The payload race progress indicator is cutoff at the bottom of the screen so you can't see the capture rate of the enemy payload.

![20210901124233_1](https://user-images.githubusercontent.com/16431476/131659776-4b36774b-c1ca-4ca7-948b-88b02bfb7a9a.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 89ff5c6fed890ff05fb13aa0a085edba96aa6b2c
