### ISSUE TITLE
Target ID health cross cuts off

### ISSUE THREAD

**Issue by Silexos** [raysfire/rayshud#181]
Sorry if this one is a bit of a silly request but I was wondering if the bottom of the health cross can extend outside of the target ID panel like the top of it does.

![targetid_healthcross](https://user-images.githubusercontent.com/85089160/133284562-832b5d00-1109-4d3a-a91e-d5da30e9debe.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 9c5c92c7da2ccdeeb6054b635048fc7f76258d8c
