### ISSUE TITLE
Smaller border icons not alligned properly 

### ISSUE THREAD

**Issue by Silexos** [raysfire/rayshud#182]
This one seems a little odd but is it possible to border the icons completely? When hovering over each icon it doesn't fully surround the option as it seems to use the same borders from the larger casual and mvm icons.

![menu_selection_border](https://user-images.githubusercontent.com/85089160/133284889-aee2e7ef-e688-4c6a-9880-4d17d2bf0502.jpg)

**Comment by CriticalFlaw** [comment]
Each button shares the same size definition and border, what can be changed is what part of the button will be visible to the user. 

To fit everything on screen, I had to truncate the height of those buttons, but the drawback was that they were going to miss the lower part of the border. So I'm aware of the graphical issue but I don't plan on addressing it at this time.
