### ISSUE TITLE
Hud bar positioning

### ISSUE THREAD

**Issue by Huso112** [raysfire/rayshud#186]
Hello!
How can i move this bars into indicated areas?

![Başlıksız](https://user-images.githubusercontent.com/63163893/135848163-ea6d5fd2-f93f-4124-b610-8478a0a1c4c4.png)

**Comment by Huso112** [comment]
And how can i change the background image.

**Comment by CriticalFlaw** [comment]
Health can be repositioned in `rayshud/resource/ui/hudplayerhealth-base.res`, find `HudPlayerHealth` and change it's xpos and ypos values for the desired result. Ammo is in `rayshud/scripts/hudlayout.res` under `HudWeaponAmmo` and charge meters are `rayshud/resource/ui/huditemeffectmeter.res`, `huditemeffectmeter_cleaver.res` and `huditemeffectmeter_sodapopper.res`.

For changing backgrounds, refer to this guide: https://steamcommunity.com/sharedfiles/filedetails/?id=1514650207
