### ISSUE TITLE
Halloween missions without bonus display strange label

### ISSUE THREAD

**Issue by thejaviertc** [raysfire/rayshud#187]
I'm not sure if it's the TF2 who adds that label or this HUD, but when you play halloween missions which doesn't have bonus missions (killing bosses), this label appears.

![imagen](https://user-images.githubusercontent.com/45662206/137886359-08dacd90-134b-4b81-96a2-66cd273f7201.png)

**Comment by CriticalFlaw** [comment]
Closing because this is a game bug on Valve's side.
