### ISSUE TITLE
Starting match countdown displays twice

### ISSUE THREAD

**Issue by thejaviertc** [raysfire/rayshud#188]
When you join a casual game that hasn't started yet, the counter displays fine, but in the last 10 seconds, the counter doubles.

![imagen](https://user-images.githubusercontent.com/45662206/137887007-0d184123-6bae-4938-ac4b-683df8f5ea2e.png)

**Comment by CriticalFlaw** [comment]
Fixed in 0ce5ddc75351c6f8f99497ff658726294a67322b
