### ISSUE TITLE
Linux font issues

### ISSUE THREAD

**Issue by DeWolfRobin** [raysfire/rayshud#189]
Hi there,

I am using this amazing HUD and I am having some issues on Linux related to the font. These issues are not due to the HUD, as I also have them in the original HUD. The issue is as followed (screenshot from original HUD):
https://imgur.com/a/vGkz6i2

This is because of the whitespace characters I presume. I have changed the chat font inside the "tf/custom/rayshud/resource/chatscheme.res" where it says ChatFont, I changed this to some native Linux fonts, but the issue remains. any ideas on how to fix this? for example edit the formatting of the chat display (Player: Text they say). Maybe this could solve the issue.

**Comment by CriticalFlaw** [comment]
There is a number of font related issues with the Linux build of TF2. Unfortunately that means I won't be able to resolve them with these HUD files and its better to report them to Valve here https://github.com/ValveSoftware/Source-1-Games with the hope of them fixing it someday.
