### ISSUE TITLE
Full sized MOTD not displaying properly

### ISSUE THREAD

**Issue by chosenbill** [raysfire/rayshud#190]
as per the title, I am not HUD maker but I have been reported this issue.

**Comment by CriticalFlaw** [comment]
Can you post a screenshot and the resolution you're using?

**Comment by chosenbill** [comment]
The people that reported to me seem to have smaller resolutions, so i have gone and tested it myself but mine is 1920x1080 I did not face the same issue, reason i didnt test it at first because noticeable amount of HUDs have it somewhat worse for full sized MOTD. But I think this is no longer the hud's (issue), hence I will suggest in Discord something.
