### ISSUE TITLE
How do I change the hud bar ingame size?

### ISSUE THREAD

**Issue by Magpue** [raysfire/rayshud#198]
I tried searching about this but could not find anything, the letters and icons are massive for some reason! Tried reinstalling it, didn't work
![eeeefe](https://github.com/raysfire/rayshud/assets/152103994/d9353378-4028-4f62-8a30-3365bcd9bda0)

**Comment by CriticalFlaw** [comment]
What resolution are you using?

**Comment by CriticalFlaw** [comment]
Closing due to lack of response
