### ISSUE TITLE
Home button not working

### ISSUE THREAD

**Issue by FantasticCrasher** [raysfire/rayshud#200]
My home server button turns into a button that I haven't seen anywhere else in the game and doesn't do anything whenever I change the 'command' value in the gamemenu.res file with anything other than 'command'

![image_2024-01-18_172152780](https://github.com/raysfire/rayshud/assets/157080011/2f67864e-b2b6-440b-ac22-90c9ada72170)

**Comment by FantasticCrasher** [comment]
This is the command I tried to have the home server button run

![Screenshot 2024-01-18 172853](https://github.com/raysfire/rayshud/assets/157080011/6c9865ea-87d4-42aa-984d-136957f1b8f9)

**Comment by CriticalFlaw** [comment]
Apologies for the late reply. The command is supposed to look like this:
![image](https://github.com/raysfire/rayshud/assets/6818236/10988ef2-7185-4ce3-839c-dc78705b4121)

You have it set incorrectly on your end which is why it's not working.

**Comment by CriticalFlaw** [comment]
Closing as the Home Button did not work because it was not configured correctly by the user. See above comment for the fix.
