### ISSUE TITLE
Engineer building panels move up to conflict with chat in spectator mode

### ISSUE THREAD

**Issue by maxisreal** [raysfire/rayshud#209]
![20240410224534_1](https://github.com/raysfire/rayshud/assets/145690663/75a75ba5-a5f9-4817-885b-5bfeafff2b26)

**Comment by CriticalFlaw** [comment]
This is already fixed in the latest version. Please verify your rayshud version and installation.

**Comment by maxisreal** [comment]
Got the hud from TF2HUD Editor. It conflicts with some mods I have installed, closing now.
