### ISSUE TITLE
teammate health & name are cut off in spectator mode

### ISSUE THREAD

**Issue by maxisreal** [raysfire/rayshud#210]
![20240411123458_1](https://github.com/raysfire/rayshud/assets/145690663/a69c5b4e-9844-42dc-8c8e-7802ad7c0d9b)
![20240411123521_1](https://github.com/raysfire/rayshud/assets/145690663/2df854b5-d5d4-4754-90c5-d7b1322b4d2e)
![20240411123521_1](https://github.com/raysfire/rayshud/assets/145690663/215d0dcf-3c33-4100-8a54-be6e29b283bb)
![20240411123454_1](https://github.com/raysfire/rayshud/assets/145690663/4befb462-de85-419e-897e-dab0df3c72ac)

**Comment by CriticalFlaw** [comment]
The spectator mode does not match the current hud. Is your copy modified?

**Comment by CriticalFlaw** [comment]
Either you have conflicting mods or an outdated version. Please check and verify.

**Comment by maxisreal** [comment]
Conflicting mods messed this up. Closing now.
