### ISSUE TITLE
hats with styles get messed up when switching teams

### ISSUE THREAD

**Issue by maxisreal** [raysfire/rayshud#211]
hats with styles, when on blu, always default to the first style. miscs with styles always default to the second while on blu. red team works fine for any styles
![20240414152840_1](https://github.com/raysfire/rayshud/assets/145690663/d838324b-5a5d-461c-90d9-8c12c5973146)
![20240414152847_1](https://github.com/raysfire/rayshud/assets/145690663/a2877d19-3fad-48e8-81d2-963b0ddd5824)
![20240414152928_1](https://github.com/raysfire/rayshud/assets/145690663/d5431654-2602-4bfb-9a63-2830ec188f3b)
![20240414152933_1](https://github.com/raysfire/rayshud/assets/145690663/9ed4297b-2327-4538-ada8-b34803addd2e)
![20240414153054_1](https://github.com/raysfire/rayshud/assets/145690663/70470cd9-fcf1-40d6-8eb6-70f518243da2)
![20240414153058_1](https://github.com/raysfire/rayshud/assets/145690663/8352a9cd-a392-40ef-897d-87ba97222085)
![20240414152713_1](https://github.com/raysfire/rayshud/assets/145690663/0287db3a-16d7-4267-92ca-5660120f2096)
![20240414152721_1](https://github.com/raysfire/rayshud/assets/145690663/740ba505-fbc4-45fa-8a6a-ee18532fd13b)

**Comment by CriticalFlaw** [comment]
That's likely the side effect of having the team switch option in the loadout screen. Unfortunately, because this is not officially supported by the game at this time it cannot be fixed with HUD files.
