### ISSUE TITLE
HUD bug: Icons for war paints skins/festivized weapons are transparent, while regular items are not.

### ISSUE THREAD

**Issue by yahhasx** [raysfire/rayshud#213]
I have bug, when the weapon with war paint skin or festivized weapon (not regular festive) are displayed transparent, on any panel, in the backpack, when you are spectating a player etc.
I know this happens when you have "mat_phong 0" and "mat_bumpmap 0" commands turned off.
And I know that this can be fixed in HUD so that the commands remain enabled, if in the file that is responsible for displaying these icons, change the value of the "use_item_rendertarget" command to "1".

I can't find the file that is responsible for displaying these icons in the panel that shows the current weapon of the player you are spectating, or when you click on player F to see his loadout.

![20240602013801_1](https://github.com/raysfire/rayshud/assets/105167226/1b53f709-ebc2-4e4a-8f55-c2b210682ad6)

Thanks <3

**Comment by CriticalFlaw** [comment]
You may be looking for this: https://github.com/raysfire/rayshud/blob/afad9fe1a8524628372836bfc29db2b878b2fc03/resource/ui/hudinspectpanel_base.res#L34

**Comment by CriticalFlaw** [comment]
Closing due to lack of response.
