### ISSUE TITLE
TargetID health is cut off

### ISSUE THREAD

**Issue by Epicbigfoot** [raysfire/rayshud#219]
![20241110202543_1](https://github.com/user-attachments/assets/b077092b-d6fe-42ee-9259-90290fe15148)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/raysfire/rayshud/commit/6617a002f8597d497aa490059c580a9b1b2a600b. Thank you for reporting.

![20241110152445_1](https://github.com/user-attachments/assets/c0f3c530-601d-4790-b28b-6cd9113fb10e)
