### ISSUE TITLE
Main menu flickers while loading

### ISSUE THREAD

**Issue by maxisreal** [raysfire/rayshud#220]
[hell.zip](https://github.com/user-attachments/files/17970462/hell.zip)

^ had to zip the video proof bc github sucks

I've tested this with both the versions available from this Github & TF2HUDEDITOR version. 
The 2021 version doesn't flicker. The latest ones do.
There's also this fun frame from one of the videos:
![insanity](https://github.com/user-attachments/assets/b79e1222-2400-42e8-840e-bd657266b1d0)
Make of it what you will.

**Comment by CriticalFlaw** [comment]
Reason for this is that there wasn't a separate file for the loading screen when first starting the game (to reduce overall mod size) and also that festive backgrounds get loaded after the main menu background. I've added the extra background file and removed the festive backgrounds because they don't look good with the rayshud menu layout.

Please download the latest version gain and let me know if that resolves it: https://github.com/raysfire/rayshud/archive/refs/heads/master.zip

**Comment by maxisreal** [comment]
[round2.zip](https://github.com/user-attachments/files/17972121/round2.zip)

I'm calling these blinks now: flickering is more constant and this only happens with the main menu.
Help me

**Comment by CriticalFlaw** [comment]
Can you check your recording? It's ~30 seconds of just your steam library

**Comment by maxisreal** [comment]
[round3.zip](https://github.com/user-attachments/files/17972216/round3.zip)

my bad gang
the flickers still happen with the new ver (take my word for it)
i switched to windowed mode and that fixed it somehow (no more blinking, but the menu still doesn't load all at once)
will visit more tomorrow

**Comment by CriticalFlaw** [comment]
Not sure what other flicker is there - the video looks fine to me.

**Comment by maxisreal** [comment]
Any updates?

**Comment by maxisreal** [comment]
disregard above
finally got footage of the latest ver flickering
[stillflickers.zip](https://github.com/user-attachments/files/17986510/stillflickers.zip)

**Comment by CriticalFlaw** [comment]
Not sure what to say - it looks like its struggling to load in time. Are you using an HDD?

**Comment by maxisreal** [comment]
Yeah but if my HDD is the problem why does the flickering not happen with the default HUD?

**Comment by CriticalFlaw** [comment]
Because it doesn't have to load any custom content of the HUD

**Comment by CriticalFlaw** [comment]
Closing as this isn't an issue that can be fixed
