### ISSUE TITLE
Embiggen target health

### ISSUE THREAD

**Issue by Samcfuchs** [raysfire/rayshud#24]
I'm a med main, and I often have trouble reading the target health on my hud. Is there any way the cross or text showing health could be sized up on the hud to make it easier to read?

As this change may not be universally preferred, maybe we could add it to the installer?

**Comment by SiIky** [comment]
I'm not entirely sure, but after browsing the HUD files i think `resource\ui\TargetID.res` is the file you wanna take a look at.
Both `TaragetNameLabel` and `TargetDataLabel` should control the name/health style respectively.
