### ISSUE TITLE
Scoreboard Layout Broken

### ISSUE THREAD

**Issue by LastTalon** [raysfire/rayshud#26]
All of the elements of the scoreboard show, but they seem to be positioned incorrectly.

**Comment by dragons4life** [comment]
I believe that's how they are supposed to be now, however I don't understand why he wouldn't want it to be centered.

**Comment by LastTalon** [comment]
Mine does not appear to be correct. Its overlapping in places and pushed against the edges of the screen.
![Imgur](http://i.imgur.com/beIyUzP.png)

**Comment by d4rklord** [comment]
Same issue here

**Comment by rakiru** [comment]
Same here. Maybe it *is* intentional? It certainly looks broken though.

**Comment by d4rklord** [comment]
I don't think so, I checked the old and new scoreboard.res files, and the positions were different than before.
Anyways, using the old version till it's fixed.

**Comment by rakiru** [comment]
I prefer the old layout anyway. It would be nice to have an easy way to switch.

**Comment by dragons4life** [comment]
Probably with the installer, doubt it tough.

**Comment by d4rklord** [comment]
Compare the previous and the current versions of ScoreBoard.res and you'll see there's a difference in xpos and ypos.

I might edit it later and put the file here.

**Comment by LastTalon** [comment]
If you get that edited file, I'd love to have it.

**Comment by d4rklord** [comment]
It shows a big dark rectangle beneath the scoreboard, if you're still interested I can post it.
