### ISSUE TITLE
move chat box to bottom?

### ISSUE THREAD

**Issue by sexyk** [raysfire/rayshud#3]
impossible to get used to. after playing tf2 for several years i cannot remember to look up for the chatbox! im not the computer person and i dont know how to edit it to make it go to the bottom, if you know how please tell me.

**Comment by laytonleader** [comment]
go to resource/ui and delete basechat.res.

**Comment by Samcfuchs** [comment]
This should really be closed. @raysfire are you paying attention to these issues?
