### ISSUE TITLE
Broken Timer Panel

### ISSUE THREAD

**Issue by lamofgod** [raysfire/rayshud#32]
The countdown does not appear when I join any server. I use 4:3 and I've already transferred the scoreboard files. Any reason for this?

**Comment by SparklySnowman** [comment]
This has happen to me aswell.

**Comment by lamofgod** [comment]
There is no timer when I tried ahud and the default HUD as well, so I think this may be a problem that Valve has to fix. Also, everyone else in servers has the same problem.

**Comment by SparklySnowman** [comment]
I think that this is only payload though, because I was in a koth server and I saw them.

**Comment by Winterzduck** [comment]
Matchmaking changed the way timers work, I think rays fixed this in the latest update though.

**Comment by SparklySnowman** [comment]
Okay

**Comment by SparklySnowman** [comment]
I'm going to redownload it. Also I asked my friend if he had the same problem and he did, but he doesn't use rayshud or default.
