### ISSUE TITLE
Jumping chat position

### ISSUE THREAD

**Issue by Thrash-td** [raysfire/rayshud#35]
Usually chat located in the bottom left corner like this: http://i.imgur.com/cDtGBpj.jpg
But sometimes it's (randomly, I suppose) it moves to the top: http://i.imgur.com/uv52Mb2.jpg
In the last example it's partially covered by the other hud elements (when inactive).

**Comment by Winterzduck** [comment]
If this problem only occurs when matchmaking then their is not much you can do about it. Valve has a lock on chat positions, for example my chat goes from middle screen to bottom left when I play comp. You could try making the chat panel the whole screen with the f0 command but I cannot guarantee that it will work.

**Comment by Thrash-td** [comment]
@Winterzduck it happened on Valve pub too: http://i.imgur.com/SAJCEHu.jpg

**Comment by Winterzduck** [comment]
Funny you mention that, I have been working on a hud myself and when testing the same issue has started happening to me. I looked around the forums a bit and haven't found a fix, I'm assuming that it is a problem with the recent matchmaking updates. There is not much you could do about it except making the wide and tall values for the chat to 0 (getting ride of it).

**Comment by Winterzduck** [comment]
I think I found the issue. In hud animations there is an event called (event CompetitiveGame_LowerChatWindow). It moves up to the top I think because that is were rays has set the default postion, just change the ypos to your own custom value and it should be fixed.

**Comment by CriticalFlaw** [comment]
Fixed in the latest version, if it still matters to anyone
