### ISSUE TITLE
Inspect health bars.

### ISSUE THREAD

**Issue by Tylody** [raysfire/rayshud#38]
The health bars of enemies _and teammates_ sometimes don't show up or are moving around at random.  Please fix this, because it will definitely mess up those who play medic. _example included of no health showing_
[2016-03-30 13-25-22.zip](https://github.com/raysfire/rayshud/files/196397/2016-03-30.13-25-22.zip)

**Comment by SiIky** [comment]
As @scrufulufugus said, most of these errors are happening because Valve is changing things. It's not really worth spending the time to find the root of these problems if they might change again tomorrow or the day after.
Also, coming here asking for someone to fix something is just unpolite.

**Comment by RedNinjaMC** [comment]
It is, in fact, an issue for rayshud.  I tried the vanilla hud, and the health inspect worked just fine.
( http://i.imgur.com/wbpk0Ru.jpg ).

**Comment by scrufulufugus** [comment]
Try a couple other custom huds check if it's a all around problem; also what files have u changed?

**Comment by RedNinjaMC** [comment]
This issue is exclusive to rayshud, because I tried voidHUD, and the health inspect worked fine. ( http://imgur.com/YB2mmcA ).

**Comment by scrufulufugus** [comment]
I'll look into it. When did the problem start?

**Comment by LastTalon** [comment]
Problem still exists. I can confirm.

**Comment by LastTalon** [comment]
As an update: I've done some testing. It appears that setting tf_hud_target_id_disable_floating_health to true (or the checkbox in advanced options) will cause the health to show in the TargetID box in the correct position. So the issue appears to be only with the floating health indicator.

**Comment by RedNinjaMC** [comment]
Ok, thanks for the tip, all we can do now is wait for raysfiyah to fix it i guess.
