### ISSUE TITLE
Respawn text overlapped in MvM

### ISSUE THREAD

**Issue by GIider** [raysfire/rayshud#4]
As you can see in the attached screenshot the "Respawn in <x> seconds" text is overlapped by the MvM symbols.

![2013-12-27_00004](https://f.cloud.github.com/assets/1463129/1813152/6f6c618e-6ea9-11e3-8826-88b9d7918abb.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/raysfire/rayshud/commit/88d8a5ebe658afc58a84d427477d902d2a5101f7
