### ISSUE TITLE
tf2 custom crosshair problem (windows 10)

### ISSUE THREAD

**Issue by ghost** [raysfire/rayshud#42]
hi

when i wanna use one of ur custom hud crosshair the game is only showing a "letter" or "number" as a crosshair and not the "actual" crosshair i want. pls help basically it only shows as a crosshair what is written in the "labeltext"

...only the Circle crosshair works :(

P.S.: sorry for my bad English

**Comment by Nufi94** [comment]
i use minmode if it matters...

**Comment by Winterzduck** [comment]
have you installed the crosshair fonts?

**Comment by Nufi94** [comment]
let's continue it on the forum/ thread :)


2016. 07. 07. 6:11 keltezéssel, Reuben Andrews írta:

**Comment by Nufi94** [comment]
imo it's part of the hud but even replacing it with fog's crossair font...well, nothing has changed

**Comment by CriticalFlaw** [comment]
A new crosshair pack has been implemented in the latest version which should hopefully work better in Windows 10
