### ISSUE TITLE
TF2 Meet your match HUD Update

### ISSUE THREAD

**Issue by funntnt** [raysfire/rayshud#43]
Custom HUD Versioning

In order to reduce crashing and broken UI elements after updates, custom HUDs now must explicitly specify the version of the TF UI with which they are compatible.

Custom HUD files must now be installed as add-ons under the tf/custom/ folder. Loose .res files extracted to the game directory will not be loaded.

Custom HUDs must now contain a file named "info.vdf" in their root folder, with the key "ui_version" set to the TF UI version with which they are compatible.

The current TF UI version is 1.

Non-HUD add-ons under tf/custom/ will continue to work without an "info.vdf" file, but may not load .res files.

---

General

Reworked the main menu

All play-related buttons are now accessible by clicking the "Find a game" button
Moved the Workshop and Replay buttons down the bottom group of mini-buttons

-Copied from the TF2 Update page of Meet your match.
## Link: http://www.teamfortress.com/?tab=updates

Update the menu, so that we can play using rayshud, and include a info.vdf that contains the TF UI version. If the TF UI version is already some where in the rayshud folder, then oops.

**Comment by Eriner** [comment]
For those wondering, the contents of the info.vdf file at the root of the rayshud directory should contain the following text:

```"ui_version" { "ui_version" "1" }```

**Comment by Schmotzi** [comment]
I am using the most current version of rayshud and it wont' work with matchmaking, when is the next updated version coming out or is there some way I can fix it myself.

**Comment by CriticalFlaw** [comment]
This has already been fixed, pls close.
