### ISSUE TITLE
The HUD doesn't seem to work anymore.

### ISSUE THREAD

**Issue by dongmaster** [raysfire/rayshud#44]
I'm running the latest version, 2016.0712, installed using the rayshud HUD installer.

Here's a screenshot showing what I mean when I say broken.

![2016-07-12_23-49-58_hl2](https://cloud.githubusercontent.com/assets/6408948/16784949/9b1d9ff0-488b-11e6-959b-b48bfb796c75.png)

**Comment by scrufulufugus** [comment]
Before I can say anything about fixing it I must ask you to install the hud manually, a guide to installing it can be found in the main readme.

**Comment by dongmaster** [comment]
Installing it manually worked. Thanks.
