### ISSUE TITLE
[Issue] Disconnected from VAC Secure server.

### ISSUE THREAD

**Issue by jdhydra** [raysfire/rayshud#47]
Hi! Recently i was playing TF2 with raysHUD. When i tried to connect to a server it said `"Something on your computer is blocking VAC Systems."` And it will not stop. I disabled RaysHUD and restarted tf2... Still happened.
Before you ask, yes i did look at the troubleshooting.

**Comment by fbis251** [comment]
"I disabled RaysHUD and restarted tf2... Still happened."
You disabled rayshud and it still happened. It's not rayshud
On Aug 30, 2016 10:41, Jack Dorland <notifications@github.com> wrote:Hi! Recently i was playing TF2 with raysHUD. When i tried to connect to a server it said "Something on your computer is blocking VAC Systems." And it will not stop. I disabled RaysHUD and restarted tf2... Still happened.
Before you ask, yes i did look at the troubleshooting.

**Comment by scrufulufugus** [comment]
It's very unlikely that a hud could cause that, the two most common causes are if you recently installed or modified a firewall or a application you are running (ex. Something to speed up the computer) is blocking the connection. I would suggest to wait a day to see if it's on valves side, if the problem still occurs try disabling all firewalls and viruse/system boost programs

**Comment by jdhydra** [comment]
*I have no antivirus, because common sense is all i need*

**Comment by jdhydra** [comment]
But ill try this! Thanks.

**Comment by Jose76Tron** [comment]
Is not hud problem, delete this post

**Comment by jdhydra** [comment]
Oh yes it is, i have no other mods in the custom folder.

**Comment by electricman226** [comment]
Custom assets aren't the only thing capable causing this. It can be your computer, or even could be your network for all we know.
