### ISSUE TITLE
health-cross issues and other things

### ISSUE THREAD

**Issue by TheSqrtMinus1** [raysfire/rayshud#49]
![20160909210152_1](https://cloud.githubusercontent.com/assets/15315481/18470384/458c2e88-797a-11e6-9762-612e3300acbe.jpg)

notice the red number, as if I was low on health. 

Normal, unglitched version (at least on my hud)
![20160909232732_1](https://cloud.githubusercontent.com/assets/15315481/18470449/94f1cd3e-797a-11e6-85df-170fe96b7d98.jpg)

Also, there's a weird issue with the number "2" being cut off on the right side.

![20160913063503_1](https://cloud.githubusercontent.com/assets/15315481/18470787/5ab1485a-797c-11e6-9ca5-5be4a1236ef8.jpg)

Notice the killstreak counter and the revenge crit counter both have cut off "2"s.

**Comment by electricman226** [comment]
2's are neing cut off, but you can blame Valve for the red low health color. Ever hear of something called hud_reloadscheme? Use it when that happens.
