### ISSUE TITLE
Some current issues with the hud.

### ISSUE THREAD

**Issue by TheSqrtMinus1** [raysfire/rayshud#51]
- some numbers are still cut off
- installer is incredibly buggy, crashes often, and occasionally requires a restart of the computer to get working properly

shoutouts to @CriticalFlaw for helping with this

**Comment by Viniuau** [comment]
That's why i returned to ToonHUD

**Comment by electricman226** [comment]
I don't believe the installer is supported by rays, but I could be easily wrong.

**Comment by CriticalFlaw** [comment]
You can probably remove the first and second bullet points from this. First one is an ingame bug, not strictly hud related and the second has been fixed
