### ISSUE TITLE
Repository doesn't contain a license

### ISSUE THREAD

**Issue by m-burg** [raysfire/rayshud#59]
http://choosealicense.com is a good resource for picking a license.

**Comment by Viniuau** [comment]
Why does it needs a license? IT'S A FRICKING HUD!!!

**Comment by SiIky** [comment]
I agree with @Viniuau, not just because "IT'S A FRICKING HUD!!!", but because if @raysfire never added a license, theres no need for one. If you want to ask him about it you can go to his stream.

**Comment by Viniuau** [comment]
Sorry, if i got a bit salty... hehe

**Comment by m-burg** [comment]
It's okay, Viniuau.

I brought this up because copyright defaults to "all rights reserved" when not including a license.
Adding a license (or just a dedicated "© raysfire 2017, all rights reserved") adds clarity for people who might be interested in forking the HUD for their own development.

This episode of [Request for commits](https://dev.to/rfc/9-open-source--licenses-with-heather-meeker), has some more information on this topic if you're interested.

**Comment by CriticalFlaw** [comment]
I like the idea but ultimately I think it's unnecessary
