### ISSUE TITLE
*Fixed*

### ISSUE THREAD

**Issue by Faethy** [raysfire/rayshud#62]
https://gyazo.com/886ee6648303293b19566d7efb8ea5e5.png
https://gyazo.com/80e268f94f38ec41d5feb94f758ff875.png
https://gyazo.com/27d22995e0fc8e0b6d959be6435ea500.png

This also happens 
https://gyazo.com/91ed569e3cea4f0807f36d7bcd6ccd19.png
https://gyazo.com/91ed569e3cea4f0807f36d7bcd6ccd19.png

I'm fine with it,it just seems out of place,ye know
Re-downloading Textures through Properties doesn't work either.

**Comment by Viniuau** [comment]
If it's fixed, then close your issue.
