### ISSUE TITLE
Can't see Players' Health

### ISSUE THREAD

**Issue by MrWheatley** [raysfire/rayshud#63]
Like the title says, I can't see my teammates' health for some reason. When I'm playing as Spy, I can't see the other teams' health.

**Comment by CriticalFlaw** [comment]
Do you still get this issue with the latest update?

**Comment by MrWheatley** [comment]
I did but I learned how to fix it. All I did was just typed in the console, “tf_hud_target_id_disable_floating_health 1”

**Comment by CriticalFlaw** [comment]
awesome
