### ISSUE TITLE
CTF event message too low

### ISSUE THREAD

**Issue by IdleGandalf** [raysfire/rayshud#69]
Taken from #67: CTF messages are little too low, they get into health/ammo numbers 

![20171021173337_1](https://user-images.githubusercontent.com/4494131/31853310-af246ef6-b686-11e7-8d7d-4cef3801a381.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in the latest version: https://github.com/raysfire/rayshud/pull/76
