### ISSUE TITLE
Mann Co. Catalog

### ISSUE THREAD

**Issue by abyssis** [raysfire/rayshud#7]
Hi,

Info regarding various type of items isn't showing up correctly in the Mann Co. Catalog.

An example using the Mann Co. Audition Reel:
![2014-06-25_00001](https://cloud.githubusercontent.com/assets/4331379/3385119/d145d526-fc65-11e3-9dc9-497ddf453674.jpg)

**Comment by CriticalFlaw** [comment]
This has been fixed in the latest version (2020.0808)
