### ISSUE TITLE
Loading screen: map and gamemode text cut off

### ISSUE THREAD

**Issue by IdleGandalf** [raysfire/rayshud#70]
Taken from #67: Map and gamemode text in loading screen is too high (topbar overlaps)

**Comment by CriticalFlaw** [comment]
This has been fixed in version 2017.1022, see file change here: https://github.com/raysfire/rayshud/commit/9cd80019d85ee471c66e674f9553549c1945f5ad#diff-7f7a1282d5475936d4d1ae162497e4b8
