### ISSUE TITLE
"New Item" and other misc. problems

### ISSUE THREAD

**Issue by GrunkleChubs** [raysfire/rayshud#73]
Firstly, whenever you get a new item, the thunder icon is where it used to be in previous versions. If you click it, the "item received" page will actually replace the background, as in the whole main menu is visible and the page basically replaces that star background. I'll try and get a picture of it.

Secondly, this is a small one, the hitbox for clicking the medal on the main menu is off to the left where it shouldn't be.

Lastly, I think this is the HUD, the "queue" box obscures the "resume game" box. Again, it'll try to get pictures of all of this.

EDIT: nvm I legit just notice it's all in 67. have a good day.

**Comment by IdleGandalf** [comment]
Close this then?

**Comment by CriticalFlaw** [comment]
Yes, this can be closed. The new items page has been fixed as of the latest version (v2017.1022) if you're still seeing the issue, just reinstall rayshud.
