### ISSUE TITLE
Crosshairs not displaying

### ISSUE THREAD

**Issue by CriticalFlaw** [raysfire/rayshud#78]
Following the Jungle Inferno Update, none of the crosshairs are displaying when turned on. There's no evidence from recent updates to suggest what could have caused this. An ideal solution would be to switch to KnuckleCrosses, they are easier to implement and maintain long term.

**Comment by fadillzzz** [comment]
That's odd. I just updated a few days ago to be able to play with the HUD after the Pyro update and the crosshair I had been using was still working. I'd check again now, but after Scream Fortress the game would just crash as previously reported in #79.

**Comment by CriticalFlaw** [comment]
Fixed as of the latest version: https://github.com/raysfire/rayshud/pull/76
