### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Asian-Rabbit** [raysfire/rayshud#79]
My tf2 keep crashing with rayshud + transparent view model when ever i join a game.
both dev and master keep crashing

**Comment by Unusually** [comment]
Mine does too, nothing really changed from yesterday, hopefully get a fix or a response soon.

**Comment by GrunkleChubs** [comment]
Can confirm as well.

**Comment by CriticalFlaw** [comment]
rayshud has a backend issue, that hasn't yet been identified and isn't fixable the same way other huds have already been patched after Scream Fortress.

**Comment by CriticalFlaw** [comment]
This has been fixed as of the latest version, v2017.10.28

**Comment by CriticalFlaw** [comment]
https://github.com/raysfire/rayshud/pull/76

**Comment by Unusually** [comment]
So fast, keep up the good work.
