### ISSUE TITLE
couple minor issues

### ISSUE THREAD

**Issue by nebrassy** [raysfire/rayshud#80]
both of those are on 29/10 release
1. message from customer support notification is unreadable
how it's shown
![](https://i.imgur.com/uHbB2dg.jpg)

stock hud
![](https://i.imgur.com/Y68PsTD.jpg)

in addition, notice in the first screenshot how the contracker button overlaps the news/blog button

thanks!

**Comment by CriticalFlaw** [comment]
Ideally I'd have the news/blog button disabled because there's no space for it. The space on the left of the contracker button is for the notification button and the right space is for the ingame buttons. Only maybe have it be right above the rayshud title

**Comment by CriticalFlaw** [comment]
I've added the fix for the MOTD button position to a new branch for the upcoming update. Can't really say if I'll fix the alerts issue in the first screenshot because I'd need the notification to display to actually fix it.
