### ISSUE TITLE
I can't change health and ammo size.

### ISSUE THREAD

**Issue by ThePotatoMaster20** [raysfire/rayshud#89]
So I've been using toonhud for a while and changed back to rayshud today, but I think the health and ammo bars are smaller than usual. Don't quote me on that though, since I'm used to toonhud. And whenever I change the height and size numbers in the files and use hud_reloadscheme it looks the same. I even tried reloading the game twice, but no result. Am I stupid or do I have to change it in another way?

**Comment by electricman226** [comment]
What exactly are you changing in the files?
You shouldn't be changing any scheme files, not necessary for the most part.

**Comment by ThePotatoMaster20** [comment]
The hud_layout file in the scripts folder (or whatever it's called) . The ammo part is in there.

**Comment by electricman226** [comment]
What you're changing is the size of the panel that contains the text -- not the size of the font.
To change the font size, go into `resource/ui/HudPlayerHealth.res` or `resource/ui/HudAmmoWeapons.res` and change all instances of the `font` keyvalues with your chosen font.

The way rays/critical/most hud developers manage their fonts is by making the names to be `FontName##`, with the last numbers being the size. Valid font names can be found in `resource\scheme\clientscheme_fonts.res`, and the default font for most of the hud elements is `CerbeticaBold`.

If you are lazy to go through the clientscheme to find valid values, these are all of the Cerbetica ones.
```
CerbeticaBold28
CerbeticaBold32
CerbeticaBold36
CerbeticaBold42
CerbeticaBold44
CerbeticaBold46
CerbeticaBold48
CerbeticaBold56
CerbeticaBold64
CerbeticaBold72
CerbeticaBold124
```

**Comment by ThePotatoMaster20** [comment]
Oh guess I was being dumb lol. Thanks a lot!
