### ISSUE TITLE
List of Issues Encountered (So Far)

### ISSUE THREAD

**Issue by GrunkleChubs** [raysfire/rayshud#95]
- Alert overlaps folder icon on main menu
- Crate #'s in backpack don't show, only "#..."
- Damage numbers are now a Red color, instead of the light blue. (It was a simple fix to change it to Green 255 and Blue 255, but the Engie metal numbers when you add metal are now light blue too.)
- A lot of overlapping of text in the main menu.

Also, this isn't really an issue but it would be nice to zoom in on the class in the loadout screen, if it isn't too much to ask.

**Comment by CriticalFlaw** [comment]
- I've fixed the Alert overlap, that will be released shortly
- I'm not seeing any text overlap on the main menu or crate # not showing in either 16:9 (1920x1080) or 4:3 (1280x1024) resolutions, what resolution are you seeing these issues in?
- Damage number color is now controlled by cvars hud_combattext_green/red/blue or in the advanced options menu.
- I've added full model rotation and high quality loadout item images

**Comment by CriticalFlaw** [comment]
Fixed the alert button overlap in the latest version https://github.com/raysfire/rayshud/commit/5fc03ee8fce26282d7f0929eaa20088992748e03

**Comment by GrunkleChubs** [comment]
I use 1366x768, as it's the native resolution of my monitor. You can see what it looks like [here](https://steamuserimages-a.akamaihd.net/ugc/914668728141644605/D54AC87125042DF8093CA3F6CDB4BA45EA7676D2/).

**Comment by CriticalFlaw** [comment]
Oh I see, this is an issue with the that's being used because the crate # value is above a 100. I'll see if I can fix that later

**Comment by GrunkleChubs** [comment]
Actually, it effects crates with numbers lower than 100 as well. I know this because I have a crate #69 (for obvious reasons) and has the same issue.

**Comment by CriticalFlaw** [comment]
Fixed the issue with that crate numbering by reducing the size of the font used, that should be all the issues for this ticket
