### ISSUE TITLE
Mann Co Store issue

### ISSUE THREAD

**Issue by Lunaversitay** [raysfire/rayshud#96]
Pretty sure it's an issue w/ the hud because it happened after I  installed the latest version but if you try to order something and the "Support Community Map Makers" pops up there's no cancel button cause it cuts off the end.

![](http://i.avasdemon.rocks/hl2_2018-03-30_22-04-05.png)

**Comment by CriticalFlaw** [comment]
Valve borked some panels, including this one for most custom HUDs. I'll see if there's a way to fix it though. Thanks!

**Comment by CriticalFlaw** [comment]
Possible culprit could be the default HUD file **resource/ui/stampdonationadd.res**

I don't think other custom HUDs use that file, but I'll try looking into it and if it's an issue with the default HUD file then notify Valve to fix it.

**Comment by CriticalFlaw** [comment]
Closing, this has been reported to Valve https://github.com/ValveSoftware/Source-1-Games/issues/2610

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/raysfire/rayshud/commit/e8b30eb8569ae998d78d360f09d5bbed499e34ff until Valve pushes out the fix
