### ISSUE TITLE
Casual map selection menu is messy

### ISSUE THREAD

**Issue by b7a** [raysfire/rayshud#97]
It displays as such on my end: https://i.imgur.com/uDg6YYP.jpg
Some text is cut off and the rank bar is misplaced.

**Comment by CriticalFlaw** [comment]
rayshud doesn't have any custom files for that matchmaking menu that's why it looks so messy. I'll have one made for the next update though

**Comment by CriticalFlaw** [comment]
Updated the matchmaking side panel UI https://github.com/raysfire/rayshud/commit/30feb7bbea02b2489ead75f0e6b36f81ca5a70ba

![img](https://puu.sh/zYksu/678e4995de.jpg)
