### ISSUE TITLE
Competitive MMR not displayed on Main Menu

### ISSUE THREAD

**Issue by Lezad** [raysfire/rayshud#98]
MMR is not shown on main screen with RaysHud but it does show on stock HUD next to the medal and below your rank.
Persists across all resolutions.

![rayshud](https://user-images.githubusercontent.com/38012729/38206372-1ca9773c-36a2-11e8-99fd-b9a1ff0a5a4b.png)
![defaulthud](https://user-images.githubusercontent.com/38012729/38206374-1cc5b686-36a2-11e8-8c45-f01dfdaab49a.png)

**Comment by CriticalFlaw** [comment]
Going to need to finish my placements to fix this lol

**Comment by Lezad** [comment]
Is there any way I can find the information you need?

**Comment by CriticalFlaw** [comment]
Not really, I'll just need to finish my placements in order to properly fix and test this for both HUDs.

**Comment by CriticalFlaw** [comment]
I've just posted a possible fix (https://github.com/raysfire/rayshud/commit/00fb64ef24d37797bde56ddd18943a6195f8daf9) to a test branch https://github.com/raysfire/rayshud/tree/test

Can you try it out and verify if it fixes the problem?

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/raysfire/rayshud/commit/14912d2b2e8f6f14b58731cf3c1e1afde4574ffc
